#!/usr/bin/ruby

require 'rubygems'
require 'interactive_editor'
require 'irb/completion'
require 'irb/ext/save-history'

IRB.conf[:PROMPT_MODE] = :SIMPLE

IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb_history"

IRB.conf[:AUTO_INDENT] = true

class Object
  # list methods which aren't in superclass
  def local_methods(obj = self)
    (obj.methods - obj.class.superclass.instance_methods).sort
  end
end

class String
  def pbcopy
    IO.popen('pbcopy', 'w') { |f| f << self }
    self
  end
end

module Kernel
  def require_relative(file)
    $:.unshift Dir.pwd
    require file
  end
end
