install phinze/cask/formula

install ack
install brew-cask
install git
install haskell-platform
install heroku-toolbelt
install highlight
install hub
install imagemagick
install macvim --override-system-vim
install node
install phantomjs
install rbenv
install reattach-to-user-namespace
install rlwrap
install ruby-build
install the_silver_searcher
install tmux
install tree
install vcprompt
install wget
install zsh
install zsh-completions
install zsh-history-substring-search
