#!/bin/sh

check_for_zsh() {
  if !(echo $SHELL | grep zsh > /dev/null)
  then
    echo "Switch to using zsh before continuing"
    exit 1
  fi

  echo "zsh ✓"
}

setup_vim() {
  if [[ ! -f ~/.config/nvim/autoload/plug.vim ]]; then
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    nvim +PlugInstall +qall
  fi

  mkdir -p ~/.config/nvim/tmp
  mkdir -p ~/.config/nvim/tmp/backup
  mkdir -p ~/.config/nvim/tmp/undo

  echo "Vim ✓"
}

setup_tmux() {
  if [[ ! -d ~/.tmux/plugins/tpm ]]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  fi

  echo "tmux ✓"
}

check_for_homebrew() {
  if [ $(uname) = "Darwin" ]; then
    if !(which brew > /dev/null)
    then
      echo "Install homebrew before continuing"
      exit 1
    fi

    echo "homebrew ✓"
  fi
}

make_local_configs() {
  touch ~/.vimrc.local
  touch ~/.tmux.conf.local
  touch ~/.zshrc.local
}

check_for_zsh
script/setup_symlinks
setup_vim
check_for_homebrew
setup_tmux
make_local_configs
