#!/bin/sh

check_for_zsh() {
  if !(echo $SHELL | grep zsh > /dev/null)
  then
    echo "Switch to using zsh before continuing"
    exit 1
  fi

  echo "zsh ✓"
}

clone_dotfiles() {
  if [[ ! -d ~/dotfiles ]]
  then
    git clone https://github.com/davidpdrsn/dotfiles.git ~/dotfiles
  fi

  echo "dotfiles repo ✓"
}

setup_symlinks() {
  for source in `find ~/dotfiles -iname "*.symlink"`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"
    rm -rf $dest
    ln -s $source $dest
  done

  if [[ ! -d ~/Library/Preferences/com.googlecode.iterm2.plist ]]
  then
    rm -rf ~/Library/Preferences/com.googlecode.iterm2.plist
    ln -s ~/dotfiles/iterm/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist
  fi

  echo "symlinks ✓"
}

setup_vim() {
  if [[ ! -d ~/.vim/bundle/vundle ]]; then
    git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    vim +BundleInstall +qall
  fi

  mkdir -p ~/.vim/tmp
  mkdir -p ~/.vim/tmp/backup
  mkdir -p ~/.vim/tmp/swap
  mkdir -p ~/.vim/tmp/undo

  echo "vim ✓"
}

check_for_homebrew() {
  if !(which brew > /dev/null)
  then
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    echo "You should consider running '~/dotfiles/script/install-brews' to install awesome brews."
  fi

  if brew doctor &> /dev/null
  then
    echo "homebrew ✓"
  else
    echo "homebrew not configured correctly. Run 'brew doctor' and see whats up."
    exit 1
  fi
}

check_for_zsh
clone_dotfiles
setup_symlinks
setup_vim
check_for_homebrew

echo "Consider running '~/dotfiles/configure_osx'"
