#!/bin/sh

brews() {
  echo '
  ag
  ghi
  highlight
  hub
  neovim
  node
  phantomjs
  rbenv
  reattach-to-user-namespace
  rlwrap
  ruby-build
  stack
  tmux
  tree
  vcprompt
  wget
  zsh
  zsh-completions
  zsh-history-substring-search
  zsh-syntax-highlighting
  ' | xargs
}

brew_installed() {
  brew list | grep $1 > /dev/null
}

install_brews() {
  for brew in $(brews)
  do
    if !(brew_installed $brew)
    then
      brew install $brew
    else
      echo "$brew already installed"
    fi
  done
}

install_gems() {
  echo '
  bundler
  activesupport
  git-smart
  interactive_editor
  rubocop
  tmuxinator
  ' | xargs gem install
}

stacks() {
  echo '
  ghc-mod
  hlint
  ' | xargs
}

install_stack_things() {
  for thing in $(stacks)
  do
    stack install $thing
  done
}

main() {
  install_brews
  install_gems
  install_stack_things
}

main
echo "nice apps ✓"
