#!/bin/sh

brews() {
  echo '
  ag
  brew-cask
  highlight
  hub
  node
  phantomjs
  rbenv
  ruby-build
  tmux
  tree
  vcprompt
  wget
  zsh
  zsh-completions
  zsh-history-substring-search
  ' | xargs
}

brew_installed() {
  brew list | grep $1 > /dev/null
}

main() {
  if !(brew_installed brew-cask)
  then
    brew tap phinze/cask
  fi

  if !(brew_installed macvim)
  then
    brew install macvim --override-system-vim
  else
    echo "macvim already installed"
  fi

  for brew in $(brews)
  do
    if !(brew_installed $brew)
    then
      brew install $brew
    else
      echo "$brew already installed"
    fi
  done
}

main
