#!/bin/sh

setup_symlinks() {
  for source in `find ~/dotfiles -iname "*.symlink"`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"
    rm -rf $dest
    ln -s $source $dest
  done

  mkdir -p $HOME/.config
  rm -rf $HOME/.config/nvim
  ln -s $HOME/dotfiles/nvim $HOME/.config/nvim
  ln -s $HOME/dotfiles/nvim/ $HOME/.vim

  echo "symlinks ✓"
}

setup_symlinks
